== RV64F Instructions

=== fcvt.l.s

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 0x2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x18, attr: 'funct5'},
]}
....


Format::
--
  fcvt.l.s rd,rs1
--

Description::
--

--

Implementation::
--
  x[rd] = f32->s64(f[rs1])
--

=== fcvt.lu.s

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 0x3},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x18, attr: 'funct5'},
]}
....

Format::
--
  fcvt.lu.s rd,rs1
--

Description::
--

--

Implementation::
--
  x[rd] = f32->u64(f[rs1])
--

=== fcvt.s.l

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 0x2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x1a, attr: 'funct5'},
]}
....

Format::
--
  fcvt.s.l rd,rs1
--

Description::
--

--

Implementation::
--
  f[rd] = s64->f32(x[rs1])
--

=== fcvt.s.lu

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 0x3},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x1a, attr: 'funct5'},
]}
....

Format::
--
  fcvt.s.lu rd,rs1
--

Description::
--

--

Implementation::
--
  f[rd] = u64->f32(x[rs1])
--
