== RV64D Instructions

=== fcvt.l.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 0x2},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 0x18, attr: 'funct5'},
]}
....

Format::
--
fcvt.l.d rd,rs1
--

Description::
--

--

Implementation::
--
  x[rd] = f64->s64(f[rs1])
--

=== fcvt.lu.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 0x3},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 0x18, attr: 'funct5'},
]}
....

Format::
--
fcvt.lu.d rd,rs1
--

Description::
--

--

Implementation::
--
x[rd] = f64->u64(f[rs1])
--

=== fmv.x.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x0},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 0x0},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 0x1c, attr: 'funct5'},
]}
....

Format::
--
fmv.x.d rd,rs1
--

Description::
--

--

Implementation::
--
  x[rd] = f[rs1][63:0]
--

=== fcvt.d.l

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 0x2},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 0x1a, attr: 'funct5'},
]}
....

Format::
--
fcvt.d.l rd,rs1
--

Description::
--

--

Implementation::
--
  f[rd] = s64->f64(x[rs1])
--

=== fcvt.d.lu

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 0x3},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 0x1a, attr: 'funct5'},
]}
....

Format::
--
fcvt.d.lu rd,rs1
--

Description::
--

--

Implementation::
--
  f[rd] = u64->f64(x[rs1])
--

=== fmv.d.x

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x0},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 0x0},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 0x1e, attr: 'funct5'},
]}
....

Format::
--
fmv.d.x rd,rs1
--

Description::
--

--

Implementation::
--
  f[rd] = x[rs1][63:0]
--
