== RV64A Instructions

=== lr.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x2f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 0x0},
  {bits:  1, name: 'aq'},
  {bits:  1, name: 'rl'},
  {bits:  5, name: 0x02},
]}
....

Format::
--
	lr.d rd,rs1
--

Description::
load a 64-bit data from the address in rs1, places value in rd, and registers a reservation on the memory address.

Implementation::
--
	x[rd] = LoadReserved64(M[x[rs1]])
--

=== sc.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x2f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  1, name: 'aq'},
  {bits:  1, name: 'rl'},
  {bits:  5, name: 0x03},
]}
....

Format::
--
	sc.d rd,rs1,rs2
--

Description::
write a 64-bit data in rs2 to the address in rs1, provided a valid reservation still exists on that address.
  SC writes zero to rd on success or a nonzero code on failure.

Implementation::
--
	x[rd] = StoreConditional64(M[x[rs1]], x[rs2])
--

=== amoswap.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x2f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  1, name: 'aq'},
  {bits:  1, name: 'rl'},
  {bits:  5, name: 0x01},
]}
....

Format::
--
	amoswap.d rd,rs2,(rs1)
--

Description::
atomically load a 64-bit data value from the address in rs1, place the value into register rd, swap the loaded value and the original 64-bit value in rs2, then store the result back to the address in rs1.

Implementation::
--
	x[rd] = AMO64(M[x[rs1]] SWAP x[rs2])
--

=== amoadd.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x2f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  1, name: 'aq'},
  {bits:  1, name: 'rl'},
  {bits:  5, name: 0x00},
]}
....

Format::
--
	amoadd.d rd,rs2,(rs1)
--

Description::
atomically load a 64-bit data value from the address in rs1, place the value into register rd, apply add the loaded value and the original 64-bit value in rs2, then store the result back to the address in rs1.

Implementation::
--
	x[rd] = AMO64(M[x[rs1]] + x[rs2])
--

=== amoxor.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x2f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  1, name: 'aq'},
  {bits:  1, name: 'rl'},
  {bits:  5, name: 0x04},
]}
....

Format::
--
	amoxor.d rd,rs2,(rs1)
--

Description::
atomically load a 64-bit data value from the address in rs1, place the value into register rd, apply xor the loaded value and the original 64-bit value in rs2, then store the result back to the address in rs1.

Implementation::
--
	x[rd] = AMO64(M[x[rs1]] ^ x[rs2])
--

=== amoand.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x2f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  1, name: 'aq'},
  {bits:  1, name: 'rl'},
  {bits:  5, name: 0x0c},
]}
....

Format::
--
	amoand.d rd,rs2,(rs1)
--

Description::
atomically load a 64-bit data value from the address in rs1, place the value into register rd, apply and the loaded value and the original 64-bit value in rs2, then store the result back to the address in rs1.

Implementation::
--
	x[rd] = AMO64(M[x[rs1]] & x[rs2])
--

=== amoor.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x2f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  1, name: 'aq'},
  {bits:  1, name: 'rl'},
  {bits:  5, name: 0x08},
]}
....

Format::
--
	amoor.d rd,rs2,(rs1)
--

Description::
atomically load a 64-bit data value from the address in rs1, place the value into register rd, apply or the loaded value and the original 64-bit value in rs2, then store the result back to the address in rs1.

Implementation::
--
	x[rd] = AMO64(M[x[rs1]] | x[rs2])
--

=== amomin.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x2f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  1, name: 'aq'},
  {bits:  1, name: 'rl'},
  {bits:  5, name: 0x10},
]}
....

Format::
--
	amomin.d rd,rs2,(rs1)
--

Description::
atomically load a 64-bit data value from the address in rs1, place the value into register rd, apply min the loaded value and the original 64-bit value in rs2, then store the result back to the address in rs1.

Implementation::
--
	x[rd] = AMO64(M[x[rs1]] MIN x[rs2])
--

=== amomax.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x2f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  1, name: 'aq'},
  {bits:  1, name: 'rl'},
  {bits:  5, name: 0x14},
]}
....

Format::
--
	amomax.d rd,rs2,(rs1)
--

Description::
atomically load a 64-bit data value from the address in rs1, place the value into register rd, apply max the loaded value and the original 64-bit value in rs2, then store the result back to the address in rs1.

Implementation::
--
	x[rd] = AMO64(M[x[rs1]] MAX x[rs2])
--

=== amominu.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x2f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  1, name: 'aq'},
  {bits:  1, name: 'rl'},
  {bits:  5, name: 0x18},
]}
....

Format::
--
	amominu.d rd,rs2,(rs1)
--

Description::
atomically load a 64-bit data value from the address in rs1, place the value into register rd, apply unsigned min the loaded value and the original 64-bit value in rs2, then store the result back to the address in rs1.

Implementation::
--
	x[rd] = AMO64(M[x[rs1]] MINU x[rs2])
--

=== amomaxu.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x2f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  1, name: 'aq'},
  {bits:  1, name: 'rl'},
  {bits:  5, name: 0x1c},
]}
....

Format::
--
	amomaxu.d rd,rs2,(rs1)
--

Description::
atomically load a 64-bit data value from the address in rs1, place the value into register rd, apply unsigned max the loaded value and the original 64-bit value in rs2, then store the result back to the address in rs1.

Implementation::
--
	x[rd] = AMO64(M[x[rs1]] MAXU x[rs2])
--
