== RV32A, RV64A Instructions

=== lr.w

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x2f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x2},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 0x0},
  {bits:  1, name: 'aq'},
  {bits:  1, name: 'rl'},
  {bits:  5, name: 0x02},
]}
....

Format::
--
	lr.w rd,rs1
--

Description::
load a word from the address in rs1, places the sign-extended value in rd, and registers a reservation on the memory address.

Implementation::
--
	x[rd] = LoadReserved32(M[x[rs1]])
--

=== sc.w

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x2f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x2},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  1, name: 'aq'},
  {bits:  1, name: 'rl'},
  {bits:  5, name: 0x03},
]}
....


Format::
--
	sc.w rd,rs1,rs2
--

Description::
write a word in rs2 to the address in rs1, provided a valid reservation still exists on that address.
  SC writes zero to rd on success or a nonzero code on failure.

Implementation::
--
	x[rd] = StoreConditional32(M[x[rs1]], x[rs2])
--

=== amoswap.w

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x2f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x2},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  1, name: 'aq'},
  {bits:  1, name: 'rl'},
  {bits:  5, name: 0x01},
]}
....

Format::
--
	amoswap.w rd,rs2,(rs1)
--

Description::
atomically load a 32-bit signed data value from the address in rs1, place the value into register rd, swap the loaded value and the original 32-bit signed value in rs2, then store the result back to the address in rs1.

Implementation::
--
	x[rd] = AMO32(M[x[rs1]] SWAP x[rs2])
--

=== amoadd.w

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x2f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x2},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  1, name: 'aq'},
  {bits:  1, name: 'rl'},
  {bits:  5, name: 0x00},
]}
....

Format::
--
	amoadd.w rd,rs2,(rs1)
--

Description::
Atomically load a 32-bit signed data value from the address in rs1, place the value into register rd, apply add the loaded value and the original 32-bit signed value in rs2, then store the result back to the address in rs1.

Implementation::
--
	x[rd] = AMO32(M[x[rs1]] + x[rs2])
--

=== amoxor.w

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x2f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x2},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  1, name: 'aq'},
  {bits:  1, name: 'rl'},
  {bits:  5, name: 0x04},
]}
....

Format::
--
	amoxor.w rd,rs2,(rs1)
--

Description::
Atomically load a 32-bit signed data value from the address in rs1, place the value into register rd, apply exclusive or the loaded value and the original 32-bit signed value in rs2, then store the result back to the address in rs1.

Implementation::
--
	x[rd] = AMO32(M[x[rs1]] ^ x[rs2])
--

=== amoand.w

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x2f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x2},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  1, name: 'aq'},
  {bits:  1, name: 'rl'},
  {bits:  5, name: 0x0c},
]}
....

Format::
--
	amoand.w rd,rs2,(rs1)
--

Description::
Atomically load a 32-bit signed data value from the address in rs1, place the value into register rd, apply and the loaded value and the original 32-bit signed value in rs2, then store the result back to the address in rs1.

Implementation::
--
	x[rd] = AMO32(M[x[rs1]] & x[rs2])
--

=== amoor.w

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x2f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x2},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  1, name: 'aq'},
  {bits:  1, name: 'rl'},
  {bits:  5, name: 0x08},
]}
....

Format::
--
	amoor.w rd,rs2,(rs1)
--

Description::
Atomically load a 32-bit signed data value from the address in rs1, place the value into register rd, apply or the loaded value and the original 32-bit signed value in rs2, then store the result back to the address in rs1.

Implementation::
--
	x[rd] = AMO32(M[x[rs1]] | x[rs2])
--

=== amomin.w

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x2f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x2},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  1, name: 'aq'},
  {bits:  1, name: 'rl'},
  {bits:  5, name: 0x10},
]}
....

Format::
--
	amomin.w rd,rs2,(rs1)
--

Description::
Atomically load a 32-bit signed data value from the address in rs1, place the value into register rd, apply min operator the loaded value and the original 32-bit signed value in rs2, then store the result back to the address in rs1.

Implementation::
--
	x[rd] = AMO32(M[x[rs1]] MIN x[rs2])
--

=== amomax.w

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x2f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x2},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  1, name: 'aq'},
  {bits:  1, name: 'rl'},
  {bits:  5, name: 0x14},
]}
....

Format::
--
	amomax.w rd,rs2,(rs1)
--

Description::
Atomically load a 32-bit signed data value from the address in rs1, place the value into register rd, apply max operator the loaded value and the original 32-bit signed value in rs2, then store the result back to the address in rs1.

Implementation::
--
	x[rd] = AMO32(M[x[rs1]] MAX x[rs2])
--

=== amominu.w

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x2f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x2},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  1, name: 'aq'},
  {bits:  1, name: 'rl'},
  {bits:  5, name: 0x18},
]}
....

Format::
--
	amominu.w rd,rs2,(rs1)
--

Description::
Atomically load a 32-bit unsigned data value from the address in rs1, place the value into register rd, apply unsigned min the loaded value and the original 32-bit unsigned value in rs2, then store the result back to the address in rs1.

Implementation::
--
	x[rd] = AMO32(M[x[rs1]] MINU x[rs2])
--

=== amomaxu.w

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x2f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x2},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  1, name: 'aq'},
  {bits:  1, name: 'rl'},
  {bits:  5, name: 0x1c},
]}
....

Format::
--
	amomaxu.w rd,rs2,(rs1)
--

Description::
Atomically load a 32-bit unsigned data value from the address in rs1, place the value into register rd, apply unsigned max the loaded value and the original 32-bit unsigned value in rs2, then store the result back to the address in rs1.

Implementation::
--
	x[rd] = AMO32(M[x[rs1]] MAXU x[rs2])
--
