== RV32A, RV64A Instructions

=== lr.w

cccc|

[width="66%",cols="16%,6%,6%,12%,12%,12%,12%,12%,12%",]
|===
|31-27 |26 |25 |24-20 |19-15 |14-12 |11-7 |6-2 |1-0
|00010 |aq |rl |00000 |rs1 |010 |rd |01011 |11
|===

Format::
  [verse]
  --
  lr.w rd,rs1
  --
Description::
  [verse]
  --
  load a word from the address in rs1, places the sign-extended value in rd, and registers a reservation on the memory address.
  --
Implementation::
  [verse]
  --
  x[rd] = LoadReserved32(M[x[rs1]])
  --

=== sc.w

cccc|

[width="66%",cols="16%,6%,6%,12%,12%,12%,12%,12%,12%",]
|===
|31-27 |26 |25 |24-20 |19-15 |14-12 |11-7 |6-2 |1-0
|00011 |aq |rl |rs2 |rs1 |010 |rd |01011 |11
|===

Format::
  [verse]
  --
  sc.w rd,rs1,rs2
  --
Description::
  [verse]
  --
  write a word in rs2 to the address in rs1, provided a valid reservation still exists on that address.
  SC writes zero to rd on success or a nonzero code on failure.
  --
Implementation::
  [verse]
  --
  x[rd] = StoreConditional32(M[x[rs1]], x[rs2])
  --

=== amoswap.w

cccc|

[width="66%",cols="16%,6%,6%,12%,12%,12%,12%,12%,12%",]
|===
|31-27 |26 |25 |24-20 |19-15 |14-12 |11-7 |6-2 |1-0
|00001 |aq |rl |rs2 |rs1 |010 |rd |01011 |11
|===

Format::
  [verse]
  --
  amoswap.w rd,rs2,(rs1)
  --
Description::
  [verse]
  --
  atomically load a 32-bit signed data value from the address in rs1, place the value into register rd, swap the loaded value and the original 32-bit signed value in rs2, then store the result back to the address in rs1.
  --
Implementation::
  [verse]
  --
  x[rd] = AMO32(M[x[rs1]] SWAP x[rs2])
  --

=== amoadd.w

cccc|

[width="66%",cols="16%,6%,6%,12%,12%,12%,12%,12%,12%",]
|===
|31-27 |26 |25 |24-20 |19-15 |14-12 |11-7 |6-2 |1-0
|00000 |aq |rl |rs2 |rs1 |010 |rd |01011 |11
|===

Format::
  [verse]
  --
  amoadd.w rd,rs2,(rs1)
  --
Description::
  [verse]
  --
  atomically load a 32-bit signed data value from the address in rs1, place the value into register rd, apply add the loaded value and the original 32-bit signed value in rs2, then store the result back to the address in rs1.
  --
Implementation::
  [verse]
  --
  x[rd] = AMO32(M[x[rs1]] + x[rs2])
  --

=== amoxor.w

cccc|

[width="66%",cols="16%,6%,6%,12%,12%,12%,12%,12%,12%",]
|===
|31-27 |26 |25 |24-20 |19-15 |14-12 |11-7 |6-2 |1-0
|00100 |aq |rl |rs2 |rs1 |010 |rd |01011 |11
|===

Format::
  [verse]
  --
  amoxor.w rd,rs2,(rs1)
  --
Description::
  [verse]
  --
  atomically load a 32-bit signed data value from the address in rs1, place the value into register rd, apply exclusive or the loaded value and the original 32-bit signed value in rs2, then store the result back to the address in rs1.
  --
Implementation::
  [verse]
  --
  x[rd] = AMO32(M[x[rs1]] ^ x[rs2])
  --

=== amoand.w

cccc|

[width="66%",cols="16%,6%,6%,12%,12%,12%,12%,12%,12%",]
|===
|31-27 |26 |25 |24-20 |19-15 |14-12 |11-7 |6-2 |1-0
|01100 |aq |rl |rs2 |rs1 |010 |rd |01011 |11
|===

Format::
  [verse]
  --
  amoand.w rd,rs2,(rs1)
  --
Description::
  [verse]
  --
  atomically load a 32-bit signed data value from the address in rs1, place the value into register rd, apply and the loaded value and the original 32-bit signed value in rs2, then store the result back to the address in rs1.
  --
Implementation::
  [verse]
  --
  x[rd] = AMO32(M[x[rs1]] & x[rs2])
  --

=== amoor.w

cccc|

[width="66%",cols="16%,6%,6%,12%,12%,12%,12%,12%,12%",]
|===
|31-27 |26 |25 |24-20 |19-15 |14-12 |11-7 |6-2 |1-0
|01000 |aq |rl |rs2 |rs1 |010 |rd |01011 |11
|===

Format::
  [verse]
  --
  amoor.w rd,rs2,(rs1)
  --
Description::
  [verse]
  --
  atomically load a 32-bit signed data value from the address in rs1, place the value into register rd, apply or the loaded value and the original 32-bit signed value in rs2, then store the result back to the address in rs1.
  --
Implementation::
  [verse]
  --
  x[rd] = AMO32(M[x[rs1]] | x[rs2])
  --

=== amomin.w

cccc|

[width="66%",cols="16%,6%,6%,12%,12%,12%,12%,12%,12%",]
|===
|31-27 |26 |25 |24-20 |19-15 |14-12 |11-7 |6-2 |1-0
|10000 |aq |rl |rs2 |rs1 |010 |rd |01011 |11
|===

Format::
  [verse]
  --
  amomin.w rd,rs2,(rs1)
  --
Description::
  [verse]
  --
  atomically load a 32-bit signed data value from the address in rs1, place the value into register rd, apply min operator the loaded value and the original 32-bit signed value in rs2, then store the result back to the address in rs1.
  --
Implementation::
  [verse]
  --
  x[rd] = AMO32(M[x[rs1]] MIN x[rs2])
  --

=== amomax.w

cccc|

[width="66%",cols="16%,6%,6%,12%,12%,12%,12%,12%,12%",]
|===
|31-27 |26 |25 |24-20 |19-15 |14-12 |11-7 |6-2 |1-0
|10100 |aq |rl |rs2 |rs1 |010 |rd |01011 |11
|===

Format::
  [verse]
  --
  amomax.w rd,rs2,(rs1)
  --
Description::
  [verse]
  --
  atomically load a 32-bit signed data value from the address in rs1, place the value into register rd, apply max operator the loaded value and the original 32-bit signed value in rs2, then store the result back to the address in rs1.
  --
Implementation::
  [verse]
  --
  x[rd] = AMO32(M[x[rs1]] MAX x[rs2])
  --

=== amominu.w

cccc|

[width="66%",cols="16%,6%,6%,12%,12%,12%,12%,12%,12%",]
|===
|31-27 |26 |25 |24-20 |19-15 |14-12 |11-7 |6-2 |1-0
|11000 |aq |rl |rs2 |rs1 |010 |rd |01011 |11
|===

Format::
  [verse]
  --
  amominu.w rd,rs2,(rs1)
  --
Description::
  [verse]
  --
  atomically load a 32-bit unsigned data value from the address in rs1, place the value into register rd, apply unsigned min the loaded value and the original 32-bit unsigned value in rs2, then store the result back to the address in rs1.
  --
Implementation::
  [verse]
  --
  x[rd] = AMO32(M[x[rs1]] MINU x[rs2])
  --

=== amomaxu.w

cccc|

[width="66%",cols="16%,6%,6%,12%,12%,12%,12%,12%,12%",]
|===
|31-27 |26 |25 |24-20 |19-15 |14-12 |11-7 |6-2 |1-0
|11100 |aq |rl |rs2 |rs1 |010 |rd |01011 |11
|===

Format::
  [verse]
  --
  amomaxu.w rd,rs2,(rs1)
  --
Description::
  [verse]
  --
  atomically load a 32-bit unsigned data value from the address in rs1, place the value into register rd, apply unsigned max the loaded value and the original 32-bit unsigned value in rs2, then store the result back to the address in rs1.
  --
Implementation::
  [verse]
  --
  x[rd] = AMO32(M[x[rs1]] MAXU x[rs2])
  --
