== RVB Instructions

=== add.uw

Format::
--
  add.uw rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x3b, attr: ['OP-32'] },
    { bits:  5, name: 'rd', type: 2},
    { bits:  3, name: 0x0, attr: ['ADD.UW'] },
    { bits:  5, name: 'rs1', type: 2},
    { bits:  5, name: 'rs2', type: 2},
    { bits:  7, name: 0x04, attr: ['ADD.UW'] },
]}
....

Description::
This instruction performs an XLEN-wide addition between rs2 and the zero-extended least-significant word of rs1.

Implementation::
[source]
--
let base = X(rs2);
let index = EXTZ(X(rs1)[31..0]);
X(rd) = base + index;
--

=== sh1add

Format::
--
  sh1add rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd', type: 2},
    { bits:  3, name: 0x2, attr: ['SH1ADD'] },
    { bits:  5, name: 'rs1', type: 2},
    { bits:  5, name: 'rs2', type: 2},
    { bits:  7, name: 0x10, attr: ['SH1ADD'] },
]}
....

Description::
This instruction shifts rs1 to the left by 1 bit and adds it to rs2.

Implementation::
[source]
--
X(rd) = X(rs2) + (X(rs1) << 1);
--

=== sh1add.uw

Format::
--
  sh1add.uw rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x3b, attr: ['OP-32'] },
    { bits:  5, name: 'rd', type: 2},
    { bits:  3, name: 0x2, attr: ['SH1ADD.UW'] },
    { bits:  5, name: 'rs1', type: 2},
    { bits:  5, name: 'rs2', type: 2},
    { bits:  7, name: 0x10, attr: ['SH1ADD.UW']  },
]}
....

Description::
This instruction performs an XLEN-wide addition of two addends.
The first addend is rs2. The second addend is the unsigned value formed by extracting the least-significant word of rs1 and shifting it left by 1 place.

Implementation::
[source]
--
let base = X(rs2);
let index = EXTZ(X(rs1)[31..0]);

X(rd) = base + (index << 1);
--

=== sh2add

Format::
--
  sh2add rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd', type: 2},
    { bits:  3, name: 0x4, attr: ['SH2ADD'] },
    { bits:  5, name: 'rs1', type: 2},
    { bits:  5, name: 'rs2', type: 2},
    { bits:  7, name: 0x10, attr: ['SH2ADD'] },
]}
....

Description::
This instruction shifts rs1 to the left by 2 places and adds it to rs2.

Implementation::
[source]
--
X(rd) = X(rs2) + (X(rs1) << 2);
--

=== sh2add.uw

Format::
--
  sh2add.uw rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x3b, attr: ['OP-32'] },
    { bits:  5, name: 'rd', type: 2},
    { bits:  3, name: 0x4, attr: ['SH2ADD.UW'] },
    { bits:  5, name: 'rs1', type: 2},
    { bits:  5, name: 'rs2', type: 2},
    { bits:  7, name: 0x10, attr: ['SH2ADD.UW'] },
]}
....

Description::
This instruction performs an XLEN-wide addition of two addends.
The first addend is rs2.
The second addend is the unsigned value formed by extracting the least-significant word of rs1 and shifting it left by 2 places.

Implementation::
[source]
--
let base = X(rs2);
let index = EXTZ(X(rs1)[31..0]);

X(rd) = base + (index << 2);
--

=== sh3add

Format::
--
  sh3add rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd', type: 2},
    { bits:  3, name: 0x6, attr: ['SH3ADD'] },
    { bits:  5, name: 'rs1', type: 2},
    { bits:  5, name: 'rs2', type: 2},
    { bits:  7, name: 0x10, attr: ['SH3ADD'] },
]}
....

Description::
This instruction shifts rs1 to the left by 3 places and adds it to rs2.

Implementation::
[source]
--
X(rd) = X(rs2) + (X(rs1) << 3);
--

=== sh3add.uw

Format::
--
  sh3add.uw rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x3b, attr: ['OP-32'] },
    { bits:  5, name: 'rd', type: 2},
    { bits:  3, name: 0x6, attr: ['SH3ADD.UW'] },
    { bits:  5, name: 'rs1', type: 2},
    { bits:  5, name: 'rs2', type: 2},
    { bits:  7, name: 0x10, attr: ['SH3ADD.UW'] },
]}
....

Description::
This instruction performs an XLEN-wide addition of two addends. The first addend is rs2. The second addend is the unsigned value formed by extracting the least-significant word of rs1 and shifting it left by 3 places.

Implementation::
[source]
--
let base = X(rs2);
let index = EXTZ(X(rs1)[31..0]);

X(rd) = base + (index << 3);
--

=== slli.uw

Format::
--
  slli.uw rd, rs1, shamt
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x1b, attr: ['OP-IMM-32'] },
    { bits:  5, name: 'rd', type: 2},
    { bits:  3, name: 0x1, attr: ['SLLI.UW'] },
    { bits:  5, name: 'rs1', type: 2},
    { bits:  6, name: 'shamt' },
    { bits:  6, name: 0x02, attr: ['SLLI.UW'] },
]}
....

Description::
This instruction takes the least-significant word of rs1, zero-extends it, and shifts it left by the immediate.

Implementation::
[source]
--
X(rd) = (EXTZ(X(rs)[31..0]) << shamt);
--

=== andn

Format::
--
  andn rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd', type: 2},
    { bits:  3, name: 0x7, attr: ['ANDN']},
    { bits:  5, name: 'rs1', type: 2},
    { bits:  5, name: 'rs2', type: 2},
    { bits:  7, name: 0x20, attr: ['ANDN'] },
]}
....

Description::
This instruction performs the bitwise logical AND operation between rs1 and the bitwise inversion of rs2.

Implementation::
[source]
--
X(rd) = X(rs1) & ~X(rs2);
--

=== orn

Format::
--
  orn rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd', type: 2},
    { bits:  3, name: 0x6, attr: ['ORN']},
    { bits:  5, name: 'rs1', type: 2},
    { bits:  5, name: 'rs2', type: 2},
    { bits:  7, name: 0x20, attr: ['ORN'] },
]}
....

Description::
This instruction performs the bitwise logical OR operation between rs1 and the bitwise inversion of rs2.

Implementation::
[source]
--
X(rd) = X(rs1) | ~X(rs2);
--

=== xnor

Format::
--
  xnor rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd', type: 2},
    { bits:  3, name: 0x4, attr: ['XNOR']},
    { bits:  5, name: 'rs1', type: 2},
    { bits:  5, name: 'rs2', type: 2},
    { bits:  7, name: 0x20, attr: ['XNOR'] },
]}
....

Description::
This instruction performs the bit-wise exclusive-NOR operation on rs1 and rs2.

Implementation::
[source]
--
X(rd) = ~(X(rs1) ^ X(rs2));
--


=== clz

Format::
--
  clz rd, rs
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x1, attr: ['CLZ']  },
    { bits:  5, name: 'rs1', type: 2 },
    { bits:  5, name: 0x0, attr: ['CLZ'] },
    { bits:  7, name: 0x30, attr: ['CLZ']  },
]}
....

Description::
This instruction counts the number of 0's before the first 1, starting at the most-significant bit (i.e., XLEN-1) and progressing to bit 0. Accordingly, if the input is 0, the output is XLEN, and if the most-significant bit of the input is a 1, the output is 0.

Implementation::
[source]
--
val HighestSetBit : forall ('N : Int), 'N >= 0. bits('N) -> int

function HighestSetBit x = {
  foreach (i from (xlen - 1) to 0 by 1 in dec)
    if [x[i]] == 0b1 then return(i) else ();
  return -1;
}

let rs = X(rs);
X[rd] = (xlen - 1) - HighestSetBit(rs);
--

=== clzw

Format::
--
  clzw rd, rs
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x1b, attr: ['OP-IMM-32'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x1, attr: ['CLZW'] },
    { bits:  5, name: 'rs1', type: 2 },
    { bits:  5, name: 0x0, attr: ['CLZW'] },
    { bits:  7, name: 0x30, attr: ['CLZW'] },
]}
....

Description::
This instruction counts the number of 0's before the first 1 starting at bit 31 and progressing to bit 0.
Accordingly, if the least-significant word is 0, the output is 32, and if the most-significant bit of the word (i.e., bit 31) is a 1, the output is 0.

Implementation::
[source]
--
val HighestSetBit32 : forall ('N : Int), 'N >= 0. bits('N) -> int

function HighestSetBit32 x = {
  foreach (i from 31 to 0 by 1 in dec)
    if [x[i]] == 0b1 then return(i) else ();
  return -1;
}

let rs = X(rs);
X[rd] = 31 - HighestSetBit(rs);
--

Implementation::
=== ctz

Format::
--
  ctz rd, rs
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x1, attr: ['CTZ/CTZW'] },
    { bits:  5, name: 'rs1', type: 2 },
    { bits:  5, name: 0x1, attr: ['CTZ/CTZW'] },
    { bits:  7, name: 0x30, attr: ['CTZ/CTZW'] },
]}
....

Description::
This instruction counts the number of 0's before the first 1, starting at the least-significant bit (i.e., 0) and progressing to the most-significant bit (i.e., XLEN-1).
Accordingly, if the input is 0, the output is XLEN, and if the least-significant bit of the input is a 1, the output is 0.

Implementation::
[source]
--
val LowestSetBit : forall ('N : Int), 'N >= 0. bits('N) -> int

function LowestSetBit x = {
  foreach (i from 0 to (xlen - 1) by 1 in dec)
    if [x[i]] == 0b1 then return(i) else ();
  return xlen;
}

let rs = X(rs);
X[rd] = LowestSetBit(rs);
--

=== ctzw

Format::
--
  ctzw rd, rs
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x1b, attr: ['OP-IMM-32'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x1, attr: ['CTZ/CTZW'] },
    { bits:  5, name: 'rs1', type: 2 },
    { bits:  5, name: 0x1, attr: ['CTZ/CTZW'] },
    { bits:  7, name: 0x30, attr: ['CTZ/CTZW'] },
]}
....

Description::
This instruction counts the number of 0's before the first 1, starting at the least-significant bit (i.e., 0) and progressing to the most-significant bit of the least-significant word (i.e., 31). Accordingly, if the least-significant word is 0, the output is 32, and if the least-significant bit of the input is a 1, the output is 0.

Implementation::
[source]
--
val LowestSetBit32 : forall ('N : Int), 'N >= 0. bits('N) -> int

function LowestSetBit32 x = {
  foreach (i from 0 to 31 by 1 in dec)
    if [x[i]] == 0b1 then return(i) else ();
  return 32;
}

let rs = X(rs);
X[rd] = LowestSetBit32(rs);
--

=== cpop

Format::
--
  cpop rd, rs
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x1, attr: ['CPOP'] },
    { bits:  5, name: 'rs1', type: 2 },
    { bits:  5, name: 0x2, attr: ['CPOP'] },
    { bits:  7, name: 0x30, attr: ['CPOP'] },
]}
....
Description::
This instructions counts the number of 1's (i.e., set bits) in the source register.

Implementation::
[source]
--
let bitcount = 0;
let rs = X(rs);

foreach (i from 0 to (xlen - 1) in inc)
    if rs[i] == 0b1 then bitcount = bitcount + 1 else ();

X[rd] = bitcount
--

.Software Hint
[NOTE, caption="SH" ]
===============================================================
This operations is known as population count, popcount, sideways sum, bit summation, or Hamming weight.

The GCC builtin function `+__builtin_popcount (unsigned int x)+` is implemented by cpop on RV32 and by *cpopw* on RV64.
The GCC builtin function `+__builtin_popcountl (unsigned long x)+` for LP64 is implemented by *cpop* on RV64.
===============================================================

=== cpopw

Format::
--
  cpopw rd, rs
--

[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x1b, attr: ['OP-IMM-32'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x1, attr: ['CPOPW'] },
    { bits:  5, name: 'rs', type: 2 },
    { bits:  5, name: 0x2, attr: ['CPOPW'] },
    { bits:  7, name: 0x30, attr: ['CPOPW'] },
]}
....
Description::
This instructions counts the number of 1's (i.e., set bits) in the least-significant word of the source register.

Implementation::
[source]
--
let bitcount = 0;
let val = X(rs);

foreach (i from 0 to 31 in inc)
    if val[i] == 0b1 then bitcount = bitcount + 1 else ();

X[rd] = bitcount
--

=== max

Format::
--
  max rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x6, attr: ['MAX']},
    { bits:  5, name: 'rs1', type: 2 },
    { bits:  5, name: 'rs2', type: 2 },
    { bits:  7, name: 0x05, attr: ['MINMAX/CLMUL'] },
]}
....

Description::
This instruction returns the larger of two signed integers.

Implementation::
[source]
--
let rs1_val = X(rs1);
let rs2_val = X(rs2);

let result = if   rs1_val <_s rs2_val
             then rs2_val
             else rs1_val;

X(rd) = result;
--

.Software Hint
[NOTE, caption="SW"]
===============================================================
Calculating the absolute value of a signed integer can be performed
using the following sequence: *neg rD,rS* followed by *max
rD,rS,rD*. When using this common sequence, it is suggested that they
are scheduled with no intervening instructions so that
implementations that are so optimized can fuse them together.
===============================================================

=== maxu

Format::
--
  maxu rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x7, attr: ['MAXU']},
    { bits:  5, name: 'rs1', type: 2 },
    { bits:  5, name: 'rs2', type: 2 },
    { bits:  7, name: 0x05, attr: ['MINMAX/CLMUL'] },
]}
....

Description::
This instruction returns the larger of two unsigned integers.

Implementation::
[source]
--
let rs1_val = X(rs1);
let rs2_val = X(rs2);

let result = if   rs1_val <_u rs2_val
             then rs2_val
             else rs1_val;

X(rd) = result;
--

=== min

Format::
--
  min rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x4, attr: ['MIN']},
    { bits:  5, name: 'rs1', type: 2 },
    { bits:  5, name: 'rs2', type: 2 },
    { bits:  7, name: 0x05, attr: ['MINMAX/CLMUL'] },
]}
....

Description::
This instruction returns the smaller of two signed integers.

Implementation::
[source]
--
let rs1_val = X(rs1);
let rs2_val = X(rs2);

let result = if   rs1_val <_s rs2_val
             then rs1_val
             else rs2_val;

X(rd) = result;
--

=== minu

Format::
--
  minu rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x5, attr: ['MINU']},
    { bits:  5, name: 'rs1', type: 2 },
    { bits:  5, name: 'rs2', type: 2 },
    { bits:  7, name: 0x05, attr: ['MINMAX/CLMUL'] },
]}
....

Description::
This instruction returns the smaller of two unsigned integers.

Implementation::
[source]
--
let rs1_val = X(rs1);
let rs2_val = X(rs2);

let result = if   rs1_val <_u rs2_val
             then rs1_val
             else rs2_val;

X(rd) = result;
--

Implementation::=== sext.b

Format::
--
  sext.b rd, rs
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x1, attr: ['SEXT.B/SEXT.H'] },
    { bits:  5, name: 'rs1', type: 2 },
    { bits:  5, name: 0x04, attr: ['SEXT.B'] },
    { bits:  7, name: 0x30 },
]}
....

Description::
This instruction sign-extends the least-significant byte in the source to XLEN by copying the most-significant bit in the byte (i.e., bit 7) to all of the more-significant bits.

Implementation::
[source]
--
X(rd) = EXTS(X(rs)[7..0]);
--

=== sext.h

Format::
--
  sext.h rd, rs
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x1, attr: ['SEXT.B/SEXT.H'] },
    { bits:  5, name: 'rs1', type: 2 },
    { bits:  5, name: 0x05, attr: ['SEXT.H'] },
    { bits:  7, name: 0x30 },
]}
....

Description::
This instruction sign-extends the least-significant halfword in rs to XLEN by copying the most-significant bit in the halfword (i.e., bit 15) to all of the more-significant bits.

Implementation::
[source]
--
X(rd) = EXTS(X(rs)[15..0]);
--

=== zext.h

Format::
--
  zext.h rd, rs
--

Encoding (RV32)::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x4, attr: ['ZEXT.H']},
    { bits:  5, name: 'rs', type: 2 },
    { bits:  5, name: 0x00 },
    { bits:  7, name: 0x04 },
]}
....

Encoding (RV64)::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x3b, attr: ['OP-32'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x4, attr: ['ZEXT.H']},
    { bits:  5, name: 'rs', type: 2 },
    { bits:  5, name: 0x00 },
    { bits:  7, name: 0x04 },
]}
....

Description::
This instruction zero-extends the least-significant halfword of the source to XLEN by inserting 0's into all of the bits more significant than 15.

Implementation::
[source]
--
X(rd) = EXTZ(X(rs)[15..0]);
--

.Note
[NOTE, caption="A" ]
===============================================================
The *zext.h* mnemonic corresponds to different instruction encodings in RV32 and RV64.
===============================================================

=== rol

Format::
--
  rol rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x1, attr: ['ROL']},
    { bits:  5, name: 'rs1', type: 2 },
    { bits:  5, name: 'rs2', type: 2 },
    { bits:  7, name: 0x30, attr: ['ROL'] },
]}
....

Description::
This instruction performs a rotate left of rs1 by the amount in least-significant log2(XLEN) bits of rs2.

Implementation::
[source]
--
let shamt = if   xlen == 32
            then X(rs2)[4..0]
            else X(rs2)[5..0];
let result = (X(rs1) << shamt) | (X(rs1) >> (xlen - shamt));

X(rd) = result;
--

=== rolw

Format::
--
  rolw rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x3b, attr: ['OP-32'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x1, attr: ['ROLW']},
    { bits:  5, name: 'rs1', type: 2 },
    { bits:  5, name: 'rs2', type: 2 },
    { bits:  7, name: 0x30, attr: ['ROLW'] },
]}
....

Description::
This instruction performs a rotate left on the least-significant word of  rs1 by the amount in least-significant 5 bits of rs2.
The resulting word value is sign-extended by copying bit 31 to all of the more-significant bits.

Implementation::
[source]
--
let rs1 = EXTZ(X(rs1)[31..0])
let shamt = X(rs2)[4..0];
let result = (rs1 << shamt) | (rs1 >> (32 - shamt));
X(rd) = EXTS(result[31..0]);
--

=== ror

Format::
--
    ror rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x5, attr: ['ROR']},
    { bits:  5, name: 'rs1', type: 2 },
    { bits:  5, name: 'rs2', type: 2 },
    { bits:  7, name: 0x30, attr: ['ROR'] },
]}
....

Description::
This instruction performs a rotate right of rs1 by the amount in least-significant log2(XLEN) bits of rs2.

Implementation::
[source]
--
    let shamt = if   xlen == 32
                then X(rs2)[4..0]
                else X(rs2)[5..0];
    let result = (X(rs1) >> shamt) | (X(rs1) << (xlen - shamt));

    X(rd) = result;
--

=== rori

Format::
--
  rori rd, rs1, _shamt_
--

Encoding (RV32)::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x5, attr: ['RORI']},
    { bits:  5, name: 'rs1', type: 2 },
    { bits:  5, name: 'shamt' },
    { bits:  7, name: 0x30, attr: ['RORI'] },
]}
....

Encoding (RV64)::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x5, attr: ['RORI']},
    { bits:  5, name: 'rs1', type: 2 },
    { bits:  6, name: 'shamt' },
    { bits:  6, name: 0x18, attr: ['RORI'] },
]}
....

Description::
This instruction performs a rotate right of rs1 by the amount in the least-significant log2(XLEN) bits of _shamt_.
For RV32, the encodings corresponding to shamt[5]=1 are reserved.

Implementation::
[source]
--
let shamt = if   xlen == 32
            then shamt[4..0]
            else shamt[5..0];
let result = (X(rs1) >> shamt) | (X(rs1) << (xlen - shamt));

X(rd) = result;
--

=== roriw

Format::
--
  roriw rd, rs1, _shamt_
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x1b, attr: ['OP-IMM-32'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x5, attr: ['RORIW']},
    { bits:  5, name: 'rs1', type: 2 },
    { bits:  5, name: 'shamt' },
    { bits:  7, name: 0x30, attr: ['RORIW'] },
]}
....

Description::
This instruction performs a rotate right on the least-significant word
of rs1 by the amount in the least-significant log2(XLEN) bits of
_shamt_.
The resulting word value is sign-extended by copying bit 31 to all of
the more-significant bits.


Implementation::
[source]
--
let rs1_data = EXTZ(X(rs1)[31..0];
let result = (rs1_data >> shamt) | (rs1_data << (32 - shamt));
X(rd) = EXTS(result[31..0]);
--

=== rorw

Format::
--
  rorw rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x3b, attr: ['OP-32'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x5, attr: ['RORW']},
    { bits:  5, name: 'rs1', type: 2 },
    { bits:  5, name: 'rs2', type: 2 },
    { bits:  7, name: 0x30, attr: ['RORW'] },
]}
....

Description::
This instruction performs a rotate right on the least-significant word of  rs1 by the amount in least-significant 5 bits of rs2.
The resultant word is sign-extended by copying bit 31 to all of the more-significant bits.

Implementation::
[source]
--
let rs1 = EXTZ(X(rs1)[31..0])
let shamt = X(rs2)[4..0];
let result = (rs1 >> shamt) | (rs1 << (32 - shamt));
X(rd) = EXTS(result);
--

=== orc.b

Format::
--
  orc.b rd, rs
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x5 },
    { bits:  5, name: 'rs', type: 2 },
    { bits: 12, name: 0x287 }
]}
....

Description::
Combines the bits within each byte using bitwise logical OR.
This sets the bits of each byte in the result rd to all zeros if no bit within the respective byte of rs is set, or to all ones if any bit within the respective byte of rs is set.

Implementation::
[source]
--
let input = X(rs);
let output : xlenbits = 0;

foreach (i from 0 to (xlen - 8) by 8) {
output[(i + 7)..i] = if   input[(i + 7)..i] == 0
                        then 0b00000000
                        else 0b11111111;
}

X[rd] = output;
--

=== rev8

Format::
--
  rev8 rd, rs
--

Encoding (RV32)::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x5 },
    { bits:  5, name: 'rs', type: 2 },
    { bits: 12, name: 0x698 }
]}
....

Encoding (RV64)::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x5 },
    { bits:  5, name: 'rs', type: 2 },
    { bits: 12, name: 0x6b8 }
]}
....

Description::
This instruction reverses the order of the bytes in rs.

Implementation::
[source]
--
let input = X(rs);
let output : xlenbits = 0;
let j = xlen - 1;

foreach (i from 0 to (xlen - 8) by 8) {
   output[i..(i + 7)] = input[(j - 7)..j];
   j = j - 8;
}

X[rd] = output
--

.Note
[NOTE, caption="A" ]
===============================================================
The *rev8* mnemonic corresponds to different instruction encodings in RV32 and RV64.
===============================================================

.Software Hint
[NOTE, caption="SH" ]
===============================================================
The byte-reverse operation is only available for the full register
width.  To emulate word-sized and halfword-sized byte-reversal,
perform a `rev8 rd,rs` followed by a `srai rd,rd,K`, where K is
XLEN-32 and XLEN-16, respectively.
===============================================================

=== clmul

Format::
--
  clmul rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x1, attr: ['CLMUL'] },
    { bits:  5, name: 'rs1', type: 2 },
    { bits:  5, name: 'rs2', type: 2 },
    { bits:  7, name: 0x5, attr: ['MINMAX/CLMUL'] },
]}
....

Description::
clmul produces the lower half of the 2·XLEN carry-less product.

Implementation::
[source]
--
let rs1_val = X(rs1);
let rs2_val = X(rs2);
let output : xlenbits = 0;

foreach (i from 0 to (xlen - 1) by 1) {
   output = if   ((rs2_val >> i) & 1)
            then output ^ (rs1_val << i);
            else output;
}

X[rd] = output
--

=== clmulh

Format::
--
  clmulh rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x3, attr: ['CLMULH'] },
    { bits:  5, name: 'rs1', type: 2 },
    { bits:  5, name: 'rs2', type: 2 },
    { bits:  7, name: 0x5, attr: ['MINMAX/CLMUL'] },
]}
....

Description::
clmulh produces the upper half of the 2·XLEN carry-less product.

Implementation::
[source]
--
let rs1_val = X(rs1);
let rs2_val = X(rs2);
let output : xlenbits = 0;

foreach (i from 1 to xlen by 1) {
   output = if   ((rs2_val >> i) & 1)
            then output ^ (rs1_val >> (xlen - i));
            else output;
}

X[rd] = output
--

=== clmulr

Format::
--
  clmulr rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd', type: 2 },
    { bits:  3, name: 0x2, attr: ['CLMULR'] },
    { bits:  5, name: 'rs1', type: 2 },
    { bits:  5, name: 'rs2', type: 2 },
    { bits:  7, name: 0x5, attr: ['MINMAX/CLMUL'] },
]}
....

Description::
*clmulr* produces bits 2·XLEN−2:XLEN-1 of the 2·XLEN carry-less
product.

Implementation::
[source]
--
let rs1_val = X(rs1);
let rs2_val = X(rs2);
let output : xlenbits = 0;

foreach (i from 0 to (xlen - 1) by 1) {
   output = if   ((rs2_val >> i) & 1)
            then output ^ (rs1_val >> (xlen - i - 1));
            else output;
}

X[rd] = output
--

.Note
[NOTE, caption="A" ]
===============================================================
The *clmulr* instruction is used to accelerate CRC calculations.
The *r* in the instruction's mnemonic stands for _reversed_, as the
instruction is equivalent to bit-reversing the inputs, performing
a *clmul*, then bit-reversing the output.
===============================================================

=== bclr

Format::
--
  bclr rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd', type: 2},
    { bits:  3, name: 0x1, attr: ['BCLR'] },
    { bits:  5, name: 'rs1', type: 2},
    { bits:  5, name: 'rs2', type: 2},
    { bits:  7, name: 0x24, attr: ['BCLR/BEXT'] },
]}
....

Description::
This instruction returns rs1 with a single bit cleared at the index specified in rs2.
The index is read from the lower log2(XLEN) bits of rs2.

Implementation::
[source]
--
let index = X(rs2) & (XLEN - 1);
X(rd) = X(rs1) & ~(1 << index)
--

=== bclri

Format::
--
  bclri rd, rs1, shamt
--

Encoding (RV32)::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd', type: 2},
    { bits:  3, name: 0x1, attr: ['BCLRI'] },
    { bits:  5, name: 'rs1', type: 2},
    { bits:  5, name: 'shamt' },
    { bits:  7, name: 0x24, attr: ['BCLRI'] },
]}
....

Encoding (RV64)::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd', type: 2},
    { bits:  3, name: 0x1, attr: ['BCLRI'] },
    { bits:  5, name: 'rs1', type: 2},
    { bits:  6, name: 'shamt' },
    { bits:  6, name: 0x12, attr: ['BCLRI'] },
]}
....

Description::
This instruction returns rs1 with a single bit cleared at the index specified in shamt.
The index is read from the lower log2(XLEN) bits of shamt.
For RV32, the encodings corresponding to shamt[5]=1 are reserved.

Implementation::
[source]
--
let index = shamt & (XLEN - 1);
X(rd) = X(rs1) & ~(1 << index)
--

=== bext

Format::
--
  bext rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd', type: 2},
    { bits:  3, name: 0x5, attr: ['BEXT'] },
    { bits:  5, name: 'rs1', type: 2},
    { bits:  5, name: 'rs2', type: 2},
    { bits:  7, name: 0x24, attr: ['BCLR/BEXT'] },
]}
....

Description::
This instruction returns a single bit extracted from rs1 at the index specified in rs2.
The index is read from the lower log2(XLEN) bits of rs2.

Implementation::
[source]
--
let index = X(rs2) & (XLEN - 1);
X(rd) = (X(rs1) >> index) & 1;
--

=== bexti

Format::
--
  bexti rd, rs1, shamt
--

Encoding (RV32)::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd', type: 2},
    { bits:  3, name: 0x5, attr: ['BEXTI'] },
    { bits:  5, name: 'rs1', type: 2},
    { bits:  5, name: 'shamt' },
    { bits:  7, name: 0x24, attr: ['BEXTI/BCLRI'] },
]}
....

Encoding (RV64)::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd', type: 2},
    { bits:  3, name: 0x5, attr: ['BEXTI'] },
    { bits:  5, name: 'rs1', type: 2},
    { bits:  6, name: 'shamt' },
    { bits:  6, name: 0x12, attr: ['BEXTI/BCLRI'] },
]}
....

Description::
This instruction returns a single bit extracted from rs1 at the index specified in shamt.
The index is read from the lower log2(XLEN) bits of shamt.
For RV32, the encodings corresponding to shamt[5]=1 are reserved.

Implementation::
[source]
--
let index = shamt & (XLEN - 1);
X(rd) = (X(rs1) >> index) & 1;
--

=== binv

Format::
--
  binv rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd', type: 2},
    { bits:  3, name: 0x1, attr: ['BINV'] },
    { bits:  5, name: 'rs1', type: 2},
    { bits:  5, name: 'rs2', type: 2},
    { bits:  7, name: 0x34, attr: ['BINV'] },
]}
....

Description::
This instruction returns rs1 with a single bit inverted at the index specified in rs2.
The index is read from the lower log2(XLEN) bits of rs2.

Implementation::
[source]
--
let index = X(rs2) & (XLEN - 1);
X(rd) = X(rs1) ^ (1 << index)
--

=== binvi

Format::
--
  binvi rd, rs1, shamt
--

Encoding (RV32)::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd', type: 2},
    { bits:  3, name: 0x1, attr: ['BINV'] },
    { bits:  5, name: 'rs1', type: 2},
    { bits:  5, name: 'shamt' },
    { bits:  7, name: 0x34, attr: ['BINVI'] },
]}
....

Encoding (RV64)::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd', type: 2},
    { bits:  3, name: 0x1, attr: ['BINV'] },
    { bits:  5, name: 'rs1', type: 2},
    { bits:  6, name: 'shamt' },
    { bits:  6, name: 0x1a, attr: ['BINVI'] },
]}
....

Description::
This instruction returns rs1 with a single bit inverted at the index specified in shamt.
The index is read from the lower log2(XLEN) bits of shamt.
For RV32, the encodings corresponding to shamt[5]=1 are reserved.

Implementation::
[source]
--
let index = shamt & (XLEN - 1);
X(rd) = X(rs1) ^ (1 << index)
--

=== bset

Format::
--
  bset rd, rs1,rs2
--

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd', type: 2},
    { bits:  3, name: 0x1, attr: ['BSET'] },
    { bits:  5, name: 'rs1', type: 2},
    { bits:  5, name: 'rs2', type: 2},
    { bits:  7, name: 0x14, attr: ['BSET'] },
]}
....

Description::
This instruction returns rs1 with a single bit set at the index specified in rs2.
The index is read from the lower log2(XLEN) bits of rs2.

Implementation::
[source]
--
let index = X(rs2) & (XLEN - 1);
X(rd) = X(rs1) | (1 << index)
--

=== bseti

Format::
--
  bseti rd, rs1,shamt
--

Encoding (RV32)::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd', type: 2},
    { bits:  3, name: 0x1, attr: ['BSETI'] },
    { bits:  5, name: 'rs1', type: 2},
    { bits:  5, name: 'shamt' },
    { bits:  7, name: 0x14, attr: ['BSETI'] },
]}
....

Encoding (RV64)::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd', type: 2},
    { bits:  3, name: 0x1, attr: ['BSETI'] },
    { bits:  5, name: 'rs1', type: 2},
    { bits:  6, name: 'shamt' },
    { bits:  6, name: 0x0a, attr: ['BSETI'] },
]}
....

Description::
This instruction returns rs1 with a single bit set at the index specified in shamt.
The index is read from the lower log2(XLEN) bits of shamt.
For RV32, the encodings corresponding to shamt[5]=1 are reserved.

Implementation::
[source]
--
let index = shamt & (XLEN - 1);
X(rd) = X(rs1) | (1 << index)
--
