== RV32F, RV64D Instructions

=== fmadd.s

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x43, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 'rs3', type: 2},
]}
....

Format::
--
fmadd.s rd,rs1,rs2,rs3
--
Description::
Perform single-precision fused multiply addition.

Implementation::
--
  f[rd] = f[rs1]×f[rs2]+f[rs3]
--

=== fmsub.s

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x47, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 'rs3', type: 2},
]}
....

Format::
--
fmsub.s rd,rs1,rs2,rs3
--
Description::
Perform single-precision fused multiply addition.

Implementation::
--
  f[rd] = f[rs1]×f[rs2]-f[rs3]
--

=== fnmsub.s

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x4b, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 'rs3', type: 2},
]}
....

Format::
--
fnmsub.s rd,rs1,rs2,rs3
--
Description::
Perform negated single-precision fused multiply subtraction.

Implementation::
--
  f[rd] = -f[rs1]×f[rs2]+f[rs3]
--

=== fnmadd.s

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x4f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 'rs3', type: 2},
]}
....

Format::
--
fnmadd.s rd,rs1,rs2,rs3
--
Description::
Perform negated single-precision fused multiply addition.

Implementation::
--
  f[rd] = -f[rs1]×f[rs2]-f[rs3]
--

=== fadd.s

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x0, attr: 'funct5'},
]}
....

Format::
--
fadd.s rd,rs1,rs2
--
Description::
Perform single-precision floating-point addition.

Implementation::
--
  f[rd] = f[rs1] + f[rs2]
--

=== fsub.s

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x1, attr: 'funct5'},
]}
....

Format::
--
fsub.s rd,rs1,rs2
--
Description::
Perform single-precision floating-point substraction.

Implementation::
--
  f[rd] = f[rs1] - f[rs2]
--

=== fmul.s

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x2, attr: 'funct5'},
]}
....

Format::
--
fmul.s rd,rs1,rs2
--
Description::
Perform single-precision floating-point multiplication.

Implementation::
--
  f[rd] = f[rs1] × f[rs2]
--

=== fdiv.s

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x3, attr: 'funct5'},
]}
....

Format::
--
fdiv.s rd,rs1,rs2
--
Description::
Perform single-precision floating-point division.

Implementation::
--
  f[rd] = f[rs1] / f[rs2]
--

=== fsqrt.s

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x0b, attr: 'funct5'},
]}
....

Format::
--
fsqrt.s rd,rs1
--
Description::
Perform single-precision square root.

Implementation::
--
  f[rd] = sqrt(f[rs1])
--

=== fsgnj.s

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x4, attr: 'funct5'},
]}
....

Format::
--
fsgnj.s rd,rs1,rs2
--
Description::
Produce a result that takes all bits except the sign bit from rs1.
  The result’s sign bit is rs2’s sign bit.

Implementation::
--
  f[rd] = {f[rs2][31], f[rs1][30:0]}
--

=== fsgnjn.s

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x4, attr: 'funct5'},
]}
....

Format::
--
fsgnjn.s rd,rs1,rs2
--
Description::
Produce a result that takes all bits except the sign bit from rs1.
  The result’s sign bit is opposite of rs2’s sign bit.

Implementation::
--
  f[rd] = {~f[rs2][31], f[rs1][30:0]}
--

=== fsgnjx.s

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x4, attr: 'funct5'},
]}
....

Format::
--
fsgnjx.s rd,rs1,rs2
--
Description::
Produce a result that takes all bits except the sign bit from rs1.
  The result’s sign bit is XOR of sign bit of rs1 and rs2.

Implementation::
--
  f[rd] = {f[rs1][31] ^ f[rs2][31], f[rs1][30:0]}
--

=== fmin.s

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x5, attr: 'funct5'},
]}
....

Format::
--
fmin.s rd,rs1,rs2
--
Description::
Write the smaller of single precision data in rs1 and rs2 to rd.

Implementation::
--
  f[rd] = min(f[rs1], f[rs2])
--

=== fmax.s

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x5, attr: 'funct5'},
]}
....

Format::
--
fmax.s rd,rs1,rs2
--
Description::
Write the larger of single precision data in rs1 and rs2 to rd.

Implementation::
--
  f[rd] = max(f[rs1], f[rs2])
--

=== fcvt.w.s

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x55, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x18, attr: 'funct5'},
]}
....

Format::
--
fcvt.w.s rd,rs1
--
Description::
Convert a floating-point number in floating-point register rs1 to a signed 32-bit in integer register rd.

Implementation::
--
  x[rd] = sext(f32->s32(f[rs1]))
--

=== fcvt.wu.s

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x18, attr: 'funct5'},
]}
....

Format::
--
fcvt.wu.s rd,rs1
--
Description::
Convert a floating-point number in floating-point register rs1 to a signed 32-bit in unsigned integer register rd.

Implementation::
--
  x[rd] = sext(f32->u32(f[rs1]))
--

=== fmv.x.w

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x0},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x1c, attr: 'funct5'},
]}
....

Format::
--
fmv.x.w rd,rs1
--
Description::
Move the single-precision value in floating-point register rs1 represented in IEEE 754-2008 encoding to the lower 32 bits of integer register rd.

Implementation::
--
  x[rd] = sext(f[rs1][31:0])
--

=== feq.s

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x2},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x14, attr: 'funct5'},
]}
....

Format::
--
feq.s rd,rs1,rs2
--
Description::
Performs a quiet equal comparison between single-precision floating-point registers rs1 and rs2 and record the Boolean result in integer register rd.
  Only signaling NaN inputs cause an Invalid Operation exception.
  The result is 0 if either operand is NaN.

Implementation::
--
  x[rd] = f[rs1] == f[rs2]
--

=== flt.s

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x14, attr: 'funct5'},
]}
....

Format::
--
flt.s rd,rs1,rs2
--
Description::
Performs a quiet less comparison between single-precision floating-point registers rs1 and rs2 and record the Boolean result in integer register rd.
  Only signaling NaN inputs cause an Invalid Operation exception.
  The result is 0 if either operand is NaN.

Implementation::
--
  x[rd] = f[rs1] < f[rs2]
--

=== fle.s


Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x14, attr: 'funct5'},
]}
....

Format::
--
fle.s rd,rs1,rs2
--
Description::
Performs a quiet less or equal comparison between single-precision floating-point registers rs1 and rs2 and record the Boolean result in integer register rd.
  Only signaling NaN inputs cause an Invalid Operation exception.
  The result is 0 if either operand is NaN.

Implementation::
--
  x[rd] = f[rs1] <= f[rs2]
--

=== fclass.s

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x1c, attr: 'funct5'},
]}
....

Format::
--
fclass.s rd,rs1
--
Description::
Examines the value in single-precision floating-point register rs1 and writes to integer register rd a 10-bit mask that indicates the class of the floating-point number.
  The format of the mask is described in [classify table]_.
  The corresponding bit in rd will be set if the property is true and clear otherwise.
  All other bits in rd are cleared. Note that exactly one bit in rd will be set.

Implementation::
--
  x[rd] = classify_s(f[rs1])
--

=== fcvt.s.w

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x1a, attr: 'funct5'},
]}
....

Format::
--
fcvt.s.w rd,rs1
--
Description::
Converts a 32-bit signed integer, in integer register rs1 into a floating-point number in floating-point register rd.

Implementation::
--
  f[rd] = s32->f32(x[rs1])
--

=== fcvt.s.wu

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x1a, attr: 'funct5'},
]}
....

Format::
--
fcvt.s.wu rd,rs1
--
Description::
Converts a 32-bit unsigned integer, in integer register rs1 into a floating-point number in floating-point register rd.

Implementation::
--
  f[rd] = u32->f32(x[rs1])
--

=== fmv.w.x

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x3e, attr: 'funct5'},
]}
....

Format::
--
fmv.w.x rd,rs1
--
Description::
Move the single-precision value encoded in IEEE 754-2008 standard encoding from the lower 32 bits of integer register rs1 to the floating-point register rd.

Implementation::
--
  f[rd] = x[rs1][31:0]
--

=== fmadd.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x43, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 'rs3', type: 2},
]}
....

Format::
--
fmadd.d rd,rs1,rs2,rs3
--
Description::
Perform double-precision fused multiply addition.

Implementation::
--
  f[rd] = f[rs1]×f[rs2]+f[rs3]
--

=== fmsub.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x47, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 'rs3', type: 2},
]}
....

Format::
--
fmsub.d rd,rs1,rs2,rs3
--
Description::
Perform double-precision fused multiply subtraction.

Implementation::
--
  f[rd] = f[rs1]×f[rs2]-f[rs3]
--

=== fnmsub.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x4b, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 'rs3', type: 2},
]}
....

Format::
--
fnmsub.d rd,rs1,rs2,rs3
--
Description::
Perform negated double-precision fused multiply subtraction.

Implementation::
--
  f[rd] = -f[rs1]×f[rs2]+f[rs3]
--

=== fnmadd.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x4f, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 'rs3', type: 2},
]}
....

Format::
--
fnmadd.d rd,rs1,rs2,rs3
--
Description::
Perform negated double-precision fused multiply addition.

Implementation::
--
  f[rd] = -f[rs1]×f[rs2]-f[rs3]
--

=== fadd.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 0x0, attr: 'funct5'},
]}
....

Format::
--
fadd.d rd,rs1,rs2
--
Description::
Perform double-precision floating-point addition.

Implementation::
--
  f[rd] = f[rs1] + f[rs2]
--

=== fsub.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 0x1, attr: 'funct5'},
]}
....

Format::
--
fsub.d rd,rs1,rs2
--
Description::
Perform double-precision floating-point addition.

Implementation::
--
  f[rd] = f[rs1] - f[rs2]
--

=== fmul.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 0x2, attr: 'funct5'},
]}
....

Format::
--
fmul.d rd,rs1,rs2
--
Description::
Perform double-precision floating-point addition.

Implementation::
--
  f[rd] = f[rs1] × f[rs2]
--

=== fdiv.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 0x3, attr: 'funct5'},
]}
....

Format::
--
fdiv.d rd,rs1,rs2
--
Description::
Perform double-precision floating-point addition.

Implementation::
--
  f[rd] = f[rs1] / f[rs2]
--

=== fsqrt.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 0x0},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 0x0b, attr: 'funct5'},
]}
....

Format::
--
fsqrt.d rd,rs1
--
Description::
Perform double-precision square root.

Implementation::
--
  f[rd] = sqrt(f[rs1])
--

=== fsgnj.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x0},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 0x4, attr: 'funct5'},
]}
....

Format::
--
fsgnj.d rd,rs1,rs2
--
Description::
Produce a result that takes all bits except the sign bit from rs1.
  The result’s sign bit is rs2’s sign bit.

Implementation::
--
  f[rd] = {f[rs2][63], f[rs1][62:0]}
--

=== fsgnjn.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x0},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 0x4, attr: 'funct5'},
]}
....

Format::
--
fsgnjn.d rd,rs1,rs2
--
Description::
Produce a result that takes all bits except the sign bit from rs1.
  The result’s sign bit is opposite of rs2’s sign bit.

Implementation::
--
  f[rd] = {~f[rs2][63], f[rs1][62:0]}
--

=== fsgnjx.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x2},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 0x4, attr: 'funct5'},
]}
....

Format::
--
fsgnjx.d rd,rs1,rs2
--
Description::
Produce a result that takes all bits except the sign bit from rs1.
  The result’s sign bit is XOR of sign bit of rs1 and rs2.

Implementation::
--
  f[rd] = {f[rs1][63] ^ f[rs2][63], f[rs1][62:0]}
--

=== fmin.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x0},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 0x5, attr: 'funct5'},
]}
....

Format::
--
fmin.d rd,rs1,rs2
--
Description::
Write the smaller of double precision data in rs1 and rs2 to rd.

Implementation::
--
  f[rd] = min(f[rs1], f[rs2])
--

=== fmax.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x1},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 0x5, attr: 'funct5'},
]}
....

Format::
--
fmax.d rd,rs1,rs2
--
Description::
Write the larger of double precision data in rs1 and rs2 to rd.

Implementation::
--
  f[rd] = max(f[rs1], f[rs2])
--

=== fcvt.s.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 0x1},
  {bits:  2, name: 0x0, attr: 'fmt'},
  {bits:  5, name: 0x8, attr: 'funct5'},
]}
....

Format::
--
fcvt.s.d rd,rs1
--
Description::
Converts double floating-point register in rs1 into a floating-point number in floating-point register rd.

Implementation::
--
  f[rd] = f64->f32(f[rs1])
--

=== fcvt.d.s

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 0x0},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 0x8, attr: 'funct5'},
]}
....

Format::
--
fcvt.d.s rd,rs1
--
Description::
Converts single floating-point register in rs1 into a double floating-point number in floating-point register rd.

Implementation::
--
  f[rd] = f32->f64(f[rs1])
--

=== feq.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x2},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 0x14, attr: 'funct5'},
]}
....

Format::
--
feq.d rd,rs1,rs2
--
Description::
Performs a quiet equal comparison between double-precision floating-point registers rs1 and rs2 and record the Boolean result in integer register rd.
  Only signaling NaN inputs cause an Invalid Operation exception.
  The result is 0 if either operand is NaN.

Implementation::
--
  x[rd] = f[rs1] == f[rs2]
--

=== flt.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x1},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 0x14, attr: 'funct5'},
]}
....

Format::
--
flt.d rd,rs1,rs2
--
Description::
Performs a quiet less comparison between double-precision floating-point registers rs1 and rs2 and record the Boolean result in integer register rd.
  Only signaling NaN inputs cause an Invalid Operation exception.
  The result is 0 if either operand is NaN.

Implementation::
--
  x[rd] = f[rs1] < f[rs2]
--

=== fle.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x0},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  2, name: 0x1, attr: 'fmt'},
  {bits:  5, name: 0x14, attr: 'funct5'},
]}
....

Format::
--
fle.d rd,rs1,rs2
--
Description::
Performs a quiet less or equal comparison between double-precision floating-point registers rs1 and rs2 and record the Boolean result in integer register rd.
  Only signaling NaN inputs cause an Invalid Operation exception.
  The result is 0 if either operand is NaN.

Implementation::
--
  x[rd] = f[rs1] <= f[rs2]
--

=== fclass.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x1},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 0x0},
  {bits:  2, name: 0x1},
  {bits:  5, name: 0x1c, attr: 'funct5'},
]}
....

Format::
--
fclass.d rd,rs1
--
Description::
Examines the value in double-precision floating-point register rs1 and writes to integer register rd a 10-bit mask that indicates the class of the floating-point number.
  The format of the mask is described in table [classify table]_.
  The corresponding bit in rd will be set if the property is true and clear otherwise.
  All other bits in rd are cleared. Note that exactly one bit in rd will be set.

Implementation::
--
  x[rd] = classifys(f[rs1])
--

=== fcvt.w.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 0x0},
  {bits:  2, name: 0x1},
  {bits:  5, name: 0x18, attr: 'funct5'},
]}
....

Format::
--
fcvt.w.d rd,rs1
--
Description::
Converts a double-precision floating-point number in floating-point register rs1 to a signed 32-bit integer, in integer register rd.

Implementation::
--
  x[rd] = sext(f64->s32(f[rs1]))
--

=== fcvt.wu.d

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 0x1},
  {bits:  2, name: 0x1},
  {bits:  5, name: 0x18, attr: 'funct5'},
]}
....

Format::
--
fcvt.wu.d rd,rs1
--
Description::
Converts a double-precision floating-point number in floating-point register rs1 to a unsigned 32-bit integer, in integer register rd.

Implementation::
--
  x[rd] = sext(u32f64(f[rs1]))
--

=== fcvt.d.w

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 0x0},
  {bits:  2, name: 0x1},
  {bits:  5, name: 0x1a, attr: 'funct5'},
]}
....

Format::
--
fcvt.d.w rd,rs1
--
Description::
Converts a 32-bit signed integer, in integer register rs1 into a double-precision floating-point number in floating-point register rd.

Implementation::
--
  x[rd] = sext(f64->s32(f[rs1]))
--

=== fcvt.d.wu

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x53, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 'rm', type: 3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 0x1},
  {bits:  2, name: 0x1},
  {bits:  5, name: 0x1a, attr: 'funct5'},
]}
....

Format::
--
fcvt.d.wu rd,rs1
--
Description::
Converts a 32-bit unsigned integer, in integer register rs1 into a double-precision floating-point number in floating-point register rd.

Implementation::
--
  f[rd] = u32->f64(x[rs1])
--

=== flw

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x07, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x2},
  {bits:  5, name: 'rs1', type: 2},
  {bits: 12, name: 'imm[11: 0]'},
]}
....

Format::
--
flw rd,offset(rs1)
--
Description::
Load a single-precision floating-point value from memory into floating-point register rd.

Implementation::
--
  f[rd] = M[x[rs1] + sext(offset)][31:0]
--

=== fsw

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x27, attr: 'opcode'},
  {bits:  5, name: 'imm[ 4: 0]'},
  {bits:  3, name: 0x2},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  7, name: 'imm[11: 5]'},
]}
....

Format::
--
fsw rs2,offset(rs1)
--
Description::
Store a single-precision value from floating-point register rs2 to memory.

Implementation::
--
  M[x[rs1] + sext(offset)] = f[rs2][31:0]
--

=== fld

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x07, attr: 'opcode'},
  {bits:  5, name: 'rd', type: 2},
  {bits:  3, name: 0x3},
  {bits:  5, name: 'rs1', type: 2},
  {bits: 12, name: 'imm[11: 0]'},
]}
....

Format::
--
fld rd,rs1,offset
--
Description::
Load a double-precision floating-point value from memory into floating-point register rd.

Implementation::
--
  f[rd] = M[x[rs1] + sext(offset)][63:0]
--

=== fsd

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits:  7, name: 0x27, attr: 'opcode'},
  {bits:  5, name: 'imm[ 4: 0]'},
  {bits:  3, name: 0x3},
  {bits:  5, name: 'rs1', type: 2},
  {bits:  5, name: 'rs2', type: 2},
  {bits:  7, name: 'imm[11: 5]'},
]}
....

Format::
--
fsd rs2,offset(rs1)
--
Description::
Store a double-precision value from the floating-point registers to memory.

Implementation::
--
  M[x[rs1] + sext(offset)] = f[rs2][63:0]
--

.Classify Table:
[width="63%",cols="20%,80%",options="header",]
|===
|rd bit |Meaning
|0 |rs1 is -infinity
|1 |rs1 is a negative normal number.
|2 |rs1 is a negative subnormal number.
|3 |rs1 is −0.
|4 |rs1 is +0.
|5 |rs1 is a positive subnormal number.
|6 |rs1 is a positive normal number.
|7 |rs1 is +infinity
|8 |rs1 is a signaling NaN.
|9 |rs1 is a quiet NaN.
|===
